
package styles

import (
    "github.com/alecthomas/chroma/v2"
)

// Frappe style.
var Frappe = (chroma.MustNewStyle("catppuccin-frappe", chroma.StyleEntries{
    chroma.Comment: "#949cbb",
    chroma.CommentHashbang: "#949cbb",
    chroma.CommentMultiline: "#949cbb",
    chroma.CommentPreproc: "#f4b8e4",
    chroma.CommentSingle: "#949cbb",
    chroma.CommentSpecial: "#949cbb",
    chroma.Generic: "#c6d0f5",
    chroma.GenericDeleted: "#e78284",
    chroma.GenericEmph: "#c6d0f5 underline",
    chroma.GenericError: "#c6d0f5",
    chroma.GenericHeading: "#c6d0f5 bold",
    chroma.GenericInserted: "#c6d0f5 bold",
    chroma.GenericOutput: "#737994",
    chroma.GenericPrompt: "#c6d0f5",
    chroma.GenericStrong: "#c6d0f5",
    chroma.GenericSubheading: "#c6d0f5 bold",
    chroma.GenericTraceback: "#c6d0f5",
    chroma.Error: "#c6d0f5",
    chroma.Keyword: "#ca9ee6",
    chroma.KeywordConstant: "#ca9ee6",
    chroma.KeywordDeclaration: "#ca9ee6 italic",
    chroma.KeywordNamespace: "#ca9ee6",
    chroma.KeywordPseudo: "#f4b8e4",
    chroma.KeywordReserved: "#ca9ee6",
    chroma.KeywordType: "#e5c890",
    chroma.Literal: "#c6d0f5",
    chroma.LiteralDate: "#c6d0f5",
    chroma.Name: "#c6d0f5",
    chroma.NameAttribute: "#a6d189",
    chroma.NameBuiltin: "#e78284 italic",
    chroma.NameBuiltinPseudo: "#e78284",
    chroma.NameClass: "#e5c890",
    chroma.NameConstant: "#c6d0f5",
    chroma.NameDecorator: "#c6d0f5",
    chroma.NameEntity: "#c6d0f5",
    chroma.NameException: "#e5c890",
    chroma.NameFunction: "#8caaee",
    chroma.NameLabel: "#81c8be italic",
    chroma.NameNamespace: "#c6d0f5",
    chroma.NameOther: "#c6d0f5",
    chroma.NameTag: "#8caaee",
    chroma.NameVariable: "#c6d0f5 italic",
    chroma.NameVariableClass: "#e5c890 italic",
    chroma.NameVariableGlobal: "#c6d0f5 italic",
    chroma.NameVariableInstance: "#c6d0f5 italic",
    chroma.LiteralNumber: "#ef9f76",
    chroma.LiteralNumberBin: "#ef9f76",
    chroma.LiteralNumberFloat: "#ef9f76",
    chroma.LiteralNumberHex: "#ef9f76",
    chroma.LiteralNumberInteger: "#ef9f76",
    chroma.LiteralNumberIntegerLong: "#ef9f76",
    chroma.LiteralNumberOct: "#ef9f76",
    chroma.Operator: "#99d1db",
    chroma.OperatorWord: "#ca9ee6",
    chroma.Other: "#c6d0f5",
    chroma.Punctuation: "#949cbb",
    chroma.LiteralString: "#a6d189",
    chroma.LiteralStringBacktick: "#a6d189",
    chroma.LiteralStringChar: "#a6d189",
    chroma.LiteralStringDoc: "#a6d189",
    chroma.LiteralStringDouble: "#a6d189",
    chroma.LiteralStringEscape: "#f4b8e4",
    chroma.LiteralStringHeredoc: "#a6d189",
    chroma.LiteralStringInterpol: "#a6d189",
    chroma.LiteralStringOther: "#a6d189",
    chroma.LiteralStringRegex: "#f4b8e4",
    chroma.LiteralStringSingle: "#a6d189",
    chroma.LiteralStringSymbol: "#e78284",
    chroma.Text: "#c6d0f5",
    chroma.TextWhitespace: "#c6d0f5",
    chroma.Background: " bg:#303446",
}))

