
package styles

import (
    "github.com/alecthomas/chroma/v2"
)

// Latte style.
var Latte = (chroma.MustNewStyle("catppuccin-latte", chroma.StyleEntries{
    chroma.Comment: "#7c7f93",
    chroma.CommentHashbang: "#7c7f93",
    chroma.CommentMultiline: "#7c7f93",
    chroma.CommentPreproc: "#ea76cb",
    chroma.CommentSingle: "#7c7f93",
    chroma.CommentSpecial: "#7c7f93",
    chroma.Generic: "#4c4f69",
    chroma.GenericDeleted: "#d20f39",
    chroma.GenericEmph: "#4c4f69 underline",
    chroma.GenericError: "#4c4f69",
    chroma.GenericHeading: "#4c4f69 bold",
    chroma.GenericInserted: "#4c4f69 bold",
    chroma.GenericOutput: "#9ca0b0",
    chroma.GenericPrompt: "#4c4f69",
    chroma.GenericStrong: "#4c4f69",
    chroma.GenericSubheading: "#4c4f69 bold",
    chroma.GenericTraceback: "#4c4f69",
    chroma.Error: "#4c4f69",
    chroma.Keyword: "#8839ef",
    chroma.KeywordConstant: "#8839ef",
    chroma.KeywordDeclaration: "#8839ef italic",
    chroma.KeywordNamespace: "#8839ef",
    chroma.KeywordPseudo: "#ea76cb",
    chroma.KeywordReserved: "#8839ef",
    chroma.KeywordType: "#df8e1d",
    chroma.Literal: "#4c4f69",
    chroma.LiteralDate: "#4c4f69",
    chroma.Name: "#4c4f69",
    chroma.NameAttribute: "#40a02b",
    chroma.NameBuiltin: "#d20f39 italic",
    chroma.NameBuiltinPseudo: "#d20f39",
    chroma.NameClass: "#df8e1d",
    chroma.NameConstant: "#4c4f69",
    chroma.NameDecorator: "#4c4f69",
    chroma.NameEntity: "#4c4f69",
    chroma.NameException: "#df8e1d",
    chroma.NameFunction: "#1e66f5",
    chroma.NameLabel: "#179299 italic",
    chroma.NameNamespace: "#4c4f69",
    chroma.NameOther: "#4c4f69",
    chroma.NameTag: "#1e66f5",
    chroma.NameVariable: "#4c4f69 italic",
    chroma.NameVariableClass: "#df8e1d italic",
    chroma.NameVariableGlobal: "#4c4f69 italic",
    chroma.NameVariableInstance: "#4c4f69 italic",
    chroma.LiteralNumber: "#fe640b",
    chroma.LiteralNumberBin: "#fe640b",
    chroma.LiteralNumberFloat: "#fe640b",
    chroma.LiteralNumberHex: "#fe640b",
    chroma.LiteralNumberInteger: "#fe640b",
    chroma.LiteralNumberIntegerLong: "#fe640b",
    chroma.LiteralNumberOct: "#fe640b",
    chroma.Operator: "#04a5e5",
    chroma.OperatorWord: "#8839ef",
    chroma.Other: "#4c4f69",
    chroma.Punctuation: "#7c7f93",
    chroma.LiteralString: "#40a02b",
    chroma.LiteralStringBacktick: "#40a02b",
    chroma.LiteralStringChar: "#40a02b",
    chroma.LiteralStringDoc: "#40a02b",
    chroma.LiteralStringDouble: "#40a02b",
    chroma.LiteralStringEscape: "#ea76cb",
    chroma.LiteralStringHeredoc: "#40a02b",
    chroma.LiteralStringInterpol: "#40a02b",
    chroma.LiteralStringOther: "#40a02b",
    chroma.LiteralStringRegex: "#ea76cb",
    chroma.LiteralStringSingle: "#40a02b",
    chroma.LiteralStringSymbol: "#d20f39",
    chroma.Text: "#4c4f69",
    chroma.TextWhitespace: "#4c4f69",
    chroma.Background: " bg:#eff1f5",
}))

