
package styles

import (
    "github.com/alecthomas/chroma/v2"
)

// Macchiato style.
var Macchiato = (chroma.MustNewStyle("catppuccin-macchiato", chroma.StyleEntries{
    chroma.Comment: "#939ab7",
    chroma.CommentHashbang: "#939ab7",
    chroma.CommentMultiline: "#939ab7",
    chroma.CommentPreproc: "#f5bde6",
    chroma.CommentSingle: "#939ab7",
    chroma.CommentSpecial: "#939ab7",
    chroma.Generic: "#cad3f5",
    chroma.GenericDeleted: "#ed8796",
    chroma.GenericEmph: "#cad3f5 underline",
    chroma.GenericError: "#cad3f5",
    chroma.GenericHeading: "#cad3f5 bold",
    chroma.GenericInserted: "#cad3f5 bold",
    chroma.GenericOutput: "#6e738d",
    chroma.GenericPrompt: "#cad3f5",
    chroma.GenericStrong: "#cad3f5",
    chroma.GenericSubheading: "#cad3f5 bold",
    chroma.GenericTraceback: "#cad3f5",
    chroma.Error: "#cad3f5",
    chroma.Keyword: "#c6a0f6",
    chroma.KeywordConstant: "#c6a0f6",
    chroma.KeywordDeclaration: "#c6a0f6 italic",
    chroma.KeywordNamespace: "#c6a0f6",
    chroma.KeywordPseudo: "#f5bde6",
    chroma.KeywordReserved: "#c6a0f6",
    chroma.KeywordType: "#eed49f",
    chroma.Literal: "#cad3f5",
    chroma.LiteralDate: "#cad3f5",
    chroma.Name: "#cad3f5",
    chroma.NameAttribute: "#a6da95",
    chroma.NameBuiltin: "#ed8796 italic",
    chroma.NameBuiltinPseudo: "#ed8796",
    chroma.NameClass: "#eed49f",
    chroma.NameConstant: "#cad3f5",
    chroma.NameDecorator: "#cad3f5",
    chroma.NameEntity: "#cad3f5",
    chroma.NameException: "#eed49f",
    chroma.NameFunction: "#8aadf4",
    chroma.NameLabel: "#8bd5ca italic",
    chroma.NameNamespace: "#cad3f5",
    chroma.NameOther: "#cad3f5",
    chroma.NameTag: "#8aadf4",
    chroma.NameVariable: "#cad3f5 italic",
    chroma.NameVariableClass: "#eed49f italic",
    chroma.NameVariableGlobal: "#cad3f5 italic",
    chroma.NameVariableInstance: "#cad3f5 italic",
    chroma.LiteralNumber: "#f5a97f",
    chroma.LiteralNumberBin: "#f5a97f",
    chroma.LiteralNumberFloat: "#f5a97f",
    chroma.LiteralNumberHex: "#f5a97f",
    chroma.LiteralNumberInteger: "#f5a97f",
    chroma.LiteralNumberIntegerLong: "#f5a97f",
    chroma.LiteralNumberOct: "#f5a97f",
    chroma.Operator: "#91d7e3",
    chroma.OperatorWord: "#c6a0f6",
    chroma.Other: "#cad3f5",
    chroma.Punctuation: "#939ab7",
    chroma.LiteralString: "#a6da95",
    chroma.LiteralStringBacktick: "#a6da95",
    chroma.LiteralStringChar: "#a6da95",
    chroma.LiteralStringDoc: "#a6da95",
    chroma.LiteralStringDouble: "#a6da95",
    chroma.LiteralStringEscape: "#f5bde6",
    chroma.LiteralStringHeredoc: "#a6da95",
    chroma.LiteralStringInterpol: "#a6da95",
    chroma.LiteralStringOther: "#a6da95",
    chroma.LiteralStringRegex: "#f5bde6",
    chroma.LiteralStringSingle: "#a6da95",
    chroma.LiteralStringSymbol: "#ed8796",
    chroma.Text: "#cad3f5",
    chroma.TextWhitespace: "#cad3f5",
    chroma.Background: " bg:#24273a",
}))

