
package styles

import (
    "github.com/alecthomas/chroma/v2"
)

// Mocha style.
var Mocha = (chroma.MustNewStyle("catppuccin-mocha", chroma.StyleEntries{
    chroma.Comment: "#9399b2",
    chroma.CommentHashbang: "#9399b2",
    chroma.CommentMultiline: "#9399b2",
    chroma.CommentPreproc: "#f5c2e7",
    chroma.CommentSingle: "#9399b2",
    chroma.CommentSpecial: "#9399b2",
    chroma.Generic: "#cdd6f4",
    chroma.GenericDeleted: "#f38ba8",
    chroma.GenericEmph: "#cdd6f4 underline",
    chroma.GenericError: "#cdd6f4",
    chroma.GenericHeading: "#cdd6f4 bold",
    chroma.GenericInserted: "#cdd6f4 bold",
    chroma.GenericOutput: "#6c7086",
    chroma.GenericPrompt: "#cdd6f4",
    chroma.GenericStrong: "#cdd6f4",
    chroma.GenericSubheading: "#cdd6f4 bold",
    chroma.GenericTraceback: "#cdd6f4",
    chroma.Error: "#cdd6f4",
    chroma.Keyword: "#cba6f7",
    chroma.KeywordConstant: "#cba6f7",
    chroma.KeywordDeclaration: "#cba6f7 italic",
    chroma.KeywordNamespace: "#cba6f7",
    chroma.KeywordPseudo: "#f5c2e7",
    chroma.KeywordReserved: "#cba6f7",
    chroma.KeywordType: "#f9e2af",
    chroma.Literal: "#cdd6f4",
    chroma.LiteralDate: "#cdd6f4",
    chroma.Name: "#cdd6f4",
    chroma.NameAttribute: "#a6e3a1",
    chroma.NameBuiltin: "#f38ba8 italic",
    chroma.NameBuiltinPseudo: "#f38ba8",
    chroma.NameClass: "#f9e2af",
    chroma.NameConstant: "#cdd6f4",
    chroma.NameDecorator: "#cdd6f4",
    chroma.NameEntity: "#cdd6f4",
    chroma.NameException: "#f9e2af",
    chroma.NameFunction: "#89b4fa",
    chroma.NameLabel: "#94e2d5 italic",
    chroma.NameNamespace: "#cdd6f4",
    chroma.NameOther: "#cdd6f4",
    chroma.NameTag: "#89b4fa",
    chroma.NameVariable: "#cdd6f4 italic",
    chroma.NameVariableClass: "#f9e2af italic",
    chroma.NameVariableGlobal: "#cdd6f4 italic",
    chroma.NameVariableInstance: "#cdd6f4 italic",
    chroma.LiteralNumber: "#fab387",
    chroma.LiteralNumberBin: "#fab387",
    chroma.LiteralNumberFloat: "#fab387",
    chroma.LiteralNumberHex: "#fab387",
    chroma.LiteralNumberInteger: "#fab387",
    chroma.LiteralNumberIntegerLong: "#fab387",
    chroma.LiteralNumberOct: "#fab387",
    chroma.Operator: "#89dceb",
    chroma.OperatorWord: "#cba6f7",
    chroma.Other: "#cdd6f4",
    chroma.Punctuation: "#9399b2",
    chroma.LiteralString: "#a6e3a1",
    chroma.LiteralStringBacktick: "#a6e3a1",
    chroma.LiteralStringChar: "#a6e3a1",
    chroma.LiteralStringDoc: "#a6e3a1",
    chroma.LiteralStringDouble: "#a6e3a1",
    chroma.LiteralStringEscape: "#f5c2e7",
    chroma.LiteralStringHeredoc: "#a6e3a1",
    chroma.LiteralStringInterpol: "#a6e3a1",
    chroma.LiteralStringOther: "#a6e3a1",
    chroma.LiteralStringRegex: "#f5c2e7",
    chroma.LiteralStringSingle: "#a6e3a1",
    chroma.LiteralStringSymbol: "#f38ba8",
    chroma.Text: "#cdd6f4",
    chroma.TextWhitespace: "#cdd6f4",
    chroma.Background: " bg:#1e1e2e",
}))

